#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello Word!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
