#!/usr/bin/env bash
# from 1 to 10 at 4 print bad luck at 8 print good luck otherwise Best school
a=0
while [ $a -lt 10 ]
do
    if [ $a -eq 4 ]; then
        echo "bad luck"
    elif [ $a -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    a=$(( a + 1 ))
done
