#!/usr/bin/env bash
# displays numbers from 1 to 20 and:
a=1
while [ $a -le 20 ]
do
    echo "$a"
    if [ $a -eq 4 ]; then
        echo "bad luck from China"
    elif [ $a -eq 9 ]; then
        echo "bad luck from Japan"
    elif [ $a -eq 17 ]; then
        echo "bad luck from Italy"
    fi
    a=$(( a + 1 ))
done
